config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :votes
  resources :comments

  resources :posts do
      resources :comments, only: [:create, :update, :show]
  end

   root 'posts#index'

   get 'upvote/:id' => 'posts#up_arrow', as: :upvote

   get 'downvote/:id' => 'posts#down_arrow', as: :downvote

   get '/r/:title' => 'subreddits#show', as: :subreddit_posts

   get 'posts/:id/fetch' => 'posts#fetch', :as => :post_fetch #Idea from Chris Vannoy

   get 'users/:id' => 'devise/registrations#show', :as => :user_profile

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, :polymorphic => true
  has_many :comments, :as => :commentable
  belongs_to :root, :polymorphic => true

  before_save :set_root

  def root_element
    commentable = self.commentable
    while commentable.is_a? Comment
      commentable = commentable.commentable
    end
    commentable
  end

  def set_root
    if commentable.is_a?(Comment) && commentable.root_id && commentable.root_type
      self.root_id = commentable.root_id
      self.root_type = commentable.root_type
    elsif commentable.is_a?(Comment) #only needed to set existing comments in DB
      self.root_id = root_element.id
      self.root_type = root_element.class.to_s
    else
      self.root_id = commentable.id
      self.root_type = commentable.class.to_s
    end

  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index #borrowed from Caleb Francis in an attempt to get comments working
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :commentable_id, :commentable_type)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="nest">
  <div class="comment">
    <p><%= comment.body %></p>
    <em><p class="comment-meta">Posted by <%=link_to comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago</p></em>
    <p><%= link_to 'permalink', comment_path(:id => comment.id) %></p>
    <% if user_signed_in? %>
      <div class="form"><%= render :partial => "comments/form", :locals => {:commentable_object => comment} %></div>
    <% end %>
    <div class="nested"><%= render :partial => "comments/comment", :collection => comment.comments %></div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= bootstrap_form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.hidden_field :commentable_id, :value => commentable_object.id %>
    <%= f.hidden_field :commentable_type, :value => commentable_object.class.to_s %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', redirect_to :back %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Commentable</th>
      <th>Commentable type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.commentable_id %></td>
        <td><%= comment.commentable_type %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path, class: "btn btn-default" %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user.email %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', post_path(@comment.commentable_id) %>