config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :votes
  resources :comments

  resources :posts do
      resources :comments, only: [:create, :update, :show]
  end

   root 'posts#index'

   get 'upvote/:id' => 'posts#up_arrow', as: :upvote

   get 'downvote/:id' => 'posts#down_arrow', as: :downvote

   get '/r/:title' => 'subreddits#show', as: :subreddit_posts

   get 'posts/:id/fetch' => 'posts#fetch', :as => :post_fetch #Idea from Chris Vannoy

   get 'users/:id' => 'devise/registrations#show', :as => :user_profile

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :votes
  belongs_to :user
  belongs_to :subreddit
  has_many :comments, :as => :commentable
  has_many :threaded_comments, :as => :root, :class_name => User

  def update_rating_cache
    self.rating_cache = self.rating
    self.save!
  end

  #Adds an upvote to active post
  def up_vote(current_user_id)
    votes << Vote.new(:up => true, :user_id => current_user_id)
  end

  #Adds a downvote to active post
  def down_vote(current_user_id)
    votes << Vote.new(:up => false, :user_id => current_user_id)
  end

  #Count upvotes
  def up_votes
    votes.where("up = ?", true).count
  end

  #Count downvotes
  def down_votes
    votes.where("up = ?", false).count
  end

  #Display post rating
  def rating
    up_votes - down_votes
  end

  def comment_counter(link, total = 0)
    if link.comments
      total += link.comments.count
      link.comments.each do |com|
        comment_counter(com, total)
      end
    end
    total
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :up_arrow, :down_arrow]
  before_action :authenticate_user!, only: [:new, :create, :update, :up_arrow, :down_arrow]
  before_filter :link_exist?, only: [:create]
  before_action :subreddit_select, only: [:new, :edit, :update, :create]
  # GET /posts
  # GET /posts.json

  #Could if params[:subreddit_id] work here to get the title from a subreddit?
  def index
    @posts = Post.order(rating_cache: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
  end

  def fetch
    @post = Post.find(params[:id])
    if current_user
      @post.up_vote(current_user.id)
    end
    redirect_to @post.url
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  def up_arrow
    @post.up_vote(current_user.id)
    redirect_to root_path
  end

  def down_arrow
    @post.down_vote(current_user.id)
    redirect_to root_path
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def subreddit_select
      @subreddit_options = Subreddit.all.collect{|subreddit| [subreddit.title, subreddit.id]}
    end

    #Check if url exists, if it does upvote the post with that url and redirect to home
    def link_exist?
      condition_result = Post.where("url =?", params[:post][:url]).empty?
      post = Post.where("url =?", params[:post][:url]).first
      if !condition_result
        redirect_to upvote_path(:id => post.id),
        notice: "Url '#{params[:post][:url]}' already exists under '#{post.title}'. You have registered an upvote on the original post. Try sharing something new!"
      end
      return condition_result
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :url, :summary, :subreddit_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= bootstrap_form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.select :subreddit_id, options_for_select(@subreddit_options, @post.subreddit_id), :prompt => "Choose a subreddit" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="row">
  <div class ="col-xs-1 post-rating">
    <% if user_signed_in? %>
      <%= link_to upvote_path(:id => post.id), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-chevron-up"></i>
      <% end %>
    <% end %>
    <h4><%= post.rating_cache %></h4>
    <% if user_signed_in? %>
      <%= link_to downvote_path(:id => post.id), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-chevron-down"></i>
      <% end %>
    <% end %>
  </div>
  <div class="col-md-2 col-sm-3 col-xs-6 pic-preview">
    <a href="<%=post.url%>" class="thumbnail">
      <img src="<%=post.url%>" onerror="this.src='<%=image_path("yaddit_guy#{%w(1 2 3 4).sample}.png")%>';" alt="Missing Image">
    </a>
  </div>
  <div class="col-md-9 col-sm-8 col-xs-5">
    <%= link_to post_fetch_path(post) do %>
      <h3 class="post-title">
        <%= post.title %>
      </h3>
    <% end %>
    <p><em>submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.email%></em></p>
    <p class="display-subreddit"><small><em> /r/<%= post.subreddit.title%></em></small></p>
    <%= link_to "#{post.comment_counter(post)} Comments", post_path(post)%>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render partial: 'post', collection: @posts %>
<% if user_signed_in? %>
  <%= link_to 'New Post', new_post_path, class: "btn btn-default" %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= render :partial => "post", :locals => {:post => @post} %>

<% if current_user %>
  <div class="form"><%= render :partial => "comments/form", :locals => {:commentable_object => @post} %></div>
<% end %>

<div class="view-comments"><%= render :partial => "comments/comment", :collection => @post.comments %></div>